//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="User.RoboticsTutorial4.Y2006.M06, Version=0.0.0.0, Culture=neutral, PublicKeyToke" +
    "n=04dc44ac2623a96f")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformUser {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.RoboticsTutorial4State), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_RoboticsTutorial4State_TO_Microsoft_Robotics_Services_RoboticsTutorial4_RoboticsTutorial4State));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.RoboticsTutorial4.RoboticsTutorial4State), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_RoboticsTutorial4_RoboticsTutorial4State_TO_Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_RoboticsTutorial4State));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.StopRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_StopRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_StopRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.RoboticsTutorial4.StopRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_RoboticsTutorial4_StopRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_StopRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.ForwardRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_ForwardRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_ForwardRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.RoboticsTutorial4.ForwardRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_RoboticsTutorial4_ForwardRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_ForwardRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.BackwardRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_BackwardRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_BackwardRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.RoboticsTutorial4.BackwardRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_RoboticsTutorial4_BackwardRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_BackwardRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.TurnLeftRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_TurnLeftRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_TurnLeftRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.RoboticsTutorial4.TurnLeftRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_RoboticsTutorial4_TurnLeftRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_TurnLeftRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.TurnRightRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_TurnRightRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_TurnRightRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.RoboticsTutorial4.TurnRightRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_RoboticsTutorial4_TurnRightRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_TurnRightRequest));
        }
        
        public static object Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_RoboticsTutorial4State_TO_Microsoft_Robotics_Services_RoboticsTutorial4_RoboticsTutorial4State(object transformFrom) {
            global::Microsoft.Robotics.Services.RoboticsTutorial4.RoboticsTutorial4State target = new global::Microsoft.Robotics.Services.RoboticsTutorial4.RoboticsTutorial4State();
            global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.RoboticsTutorial4State from = ((global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.RoboticsTutorial4State)(transformFrom));
            target.MotorEnabled = from.MotorEnabled;
            return target;
        }
        
        public static object Microsoft_Robotics_Services_RoboticsTutorial4_RoboticsTutorial4State_TO_Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_RoboticsTutorial4State(object transformFrom) {
            global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.RoboticsTutorial4State target = new global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.RoboticsTutorial4State();
            global::Microsoft.Robotics.Services.RoboticsTutorial4.RoboticsTutorial4State from = ((global::Microsoft.Robotics.Services.RoboticsTutorial4.RoboticsTutorial4State)(transformFrom));
            target.MotorEnabled = from.MotorEnabled;
            return target;
        }
        
        private static global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.StopRequest _cachedInstance0 = new global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.StopRequest();
        
        private static global::Microsoft.Robotics.Services.RoboticsTutorial4.StopRequest _cachedInstance = new global::Microsoft.Robotics.Services.RoboticsTutorial4.StopRequest();
        
        public static object Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_StopRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_StopRequest(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object Microsoft_Robotics_Services_RoboticsTutorial4_StopRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_StopRequest(object transformFrom) {
            return _cachedInstance0;
        }
        
        private static global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.ForwardRequest _cachedInstance2 = new global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.ForwardRequest();
        
        private static global::Microsoft.Robotics.Services.RoboticsTutorial4.ForwardRequest _cachedInstance1 = new global::Microsoft.Robotics.Services.RoboticsTutorial4.ForwardRequest();
        
        public static object Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_ForwardRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_ForwardRequest(object transformFrom) {
            return _cachedInstance1;
        }
        
        public static object Microsoft_Robotics_Services_RoboticsTutorial4_ForwardRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_ForwardRequest(object transformFrom) {
            return _cachedInstance2;
        }
        
        private static global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.BackwardRequest _cachedInstance4 = new global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.BackwardRequest();
        
        private static global::Microsoft.Robotics.Services.RoboticsTutorial4.BackwardRequest _cachedInstance3 = new global::Microsoft.Robotics.Services.RoboticsTutorial4.BackwardRequest();
        
        public static object Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_BackwardRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_BackwardRequest(object transformFrom) {
            return _cachedInstance3;
        }
        
        public static object Microsoft_Robotics_Services_RoboticsTutorial4_BackwardRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_BackwardRequest(object transformFrom) {
            return _cachedInstance4;
        }
        
        private static global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.TurnLeftRequest _cachedInstance6 = new global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.TurnLeftRequest();
        
        private static global::Microsoft.Robotics.Services.RoboticsTutorial4.TurnLeftRequest _cachedInstance5 = new global::Microsoft.Robotics.Services.RoboticsTutorial4.TurnLeftRequest();
        
        public static object Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_TurnLeftRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_TurnLeftRequest(object transformFrom) {
            return _cachedInstance5;
        }
        
        public static object Microsoft_Robotics_Services_RoboticsTutorial4_TurnLeftRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_TurnLeftRequest(object transformFrom) {
            return _cachedInstance6;
        }
        
        private static global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.TurnRightRequest _cachedInstance8 = new global::Microsoft.Robotics.Services.RoboticsTutorial4.Proxy.TurnRightRequest();
        
        private static global::Microsoft.Robotics.Services.RoboticsTutorial4.TurnRightRequest _cachedInstance7 = new global::Microsoft.Robotics.Services.RoboticsTutorial4.TurnRightRequest();
        
        public static object Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_TurnRightRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_TurnRightRequest(object transformFrom) {
            return _cachedInstance7;
        }
        
        public static object Microsoft_Robotics_Services_RoboticsTutorial4_TurnRightRequest_TO_Microsoft_Robotics_Services_RoboticsTutorial4_Proxy_TurnRightRequest(object transformFrom) {
            return _cachedInstance8;
        }
    }
}
